{% set name = "zen3geo" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zen3geo-{{ version }}.tar.gz
  sha256: 68dce3efa73107c649cc365da8fbd15ef7a01df701f460b4b13620f23f50a3be

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry >=1.2.0rc2
    - python >=3.8,<3.12
  run:
    - python >=3.8,<3.12
    - rioxarray >=0.10.0
    - torchdata >=0.4.0

test:
  imports:
    - zen3geo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://zen3geo.readthedocs.io
  summary: The 🌏 data science library you've been waiting for~
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE.md
  doc_url: https://zen3geo.readthedocs.io
  dev_url: https://github.com/weiji14/zen3geo

extra:
  recipe-maintainers:
    - weiji14
